### ISSUE TITLE
Issue while trying to run repo

### ISSUE THREAD

**Issue by Dome-s** [JZCS2018/SMAT#1]
Hello, i am currently trying to get this repo to run, but i am facing the following issue 
maybe this occurs because i downloaded the wrong glove.[...].txt as they were not present in the repo or my testDataset(i named them train_webform,test_webform,val_webform for ease of use but they are not the real webform dataset and rather a try on copying the formet presented in the paper to this repo) i am trying to use has the wrong format, or there is an issue in the code?

any help or additional information on what is needed to run this would be greatly appreciated, thanks in advance 

```
>>> hops: 3
>>> device: cuda:0
>>> seed: 2345
>>> valset_ratio: 0
>>> local_context_focus: cdm
>>> SRD: 3
>>> model_class: <class 'models.aoa.AOA'>
>>> dataset_file: {'train': './datasets/omap/train_webform.xlsx', 'val': './datasets/omap/val_webform.xlsx', 'test': './datasets/omap/t
est_webform.xlsx'}
>>> inputs_cols: ['text_raw_indices1', 'aspect_indices1', 'text_raw_indices2', 'aspect_indices2']
>>> optimizer_rec: sgd
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
epoch: 1
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [92,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [93,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [94,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [95,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [32,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [33,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [34,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [35,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [36,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [37,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [38,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [39,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [40,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [41,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [42,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [43,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [44,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [45,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [46,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [47,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [48,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [49,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [50,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [51,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [52,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [53,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [54,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [55,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [56,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [57,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [58,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [59,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [60,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [61,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [62,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [63,0,0] Assertion `srcIndex < sr
cSelectDimSize` failed.
Traceback (most recent call last):
  File "path\SMAT\train.py", line 346, in <module>
    main()
  File "path\SMAT\train.py", line 342, in main
    ins.run()
  File "path\Repos\SMAT\train.py", line 208, in run
    best_model_path = self._train(criterion, optimizer, train_data_loader, val_data_loader, self.opt.lrshrink, self.opt.minlr)
  File "path\SMAT\train.py", line 104, in _train
    outputs = self.model(inputs)
  File "path\anaconda3\envs\SMAT\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "path\SMAT\models\aoa.py", line 34, in forward
    ctx1 = self.embed(text_raw_indices1)
  File "path\anaconda3\envs\SMAT\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "path\anaconda3\envs\SMAT\lib\site-packages\torch\nn\modules\sparse.py", line 162, in forward
    return F.embedding(
  File "path\anaconda3\envs\SMAT\lib\site-packages\torch\nn\functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by JZCS2018** [comment]
> Hello, i am currently trying to get this repo to run, but i am facing the following issue maybe this occurs because i downloaded the wrong glove.[...].txt as they were not present in the repo or my testDataset(i named them train_webform,test_webform,val_webform for ease of use but they are not the real webform dataset and rather a try on copying the formet presented in the paper to this repo) i am trying to use has the wrong format, or there is an issue in the code?
> 
> any help or additional information on what is needed to run this would be greatly appreciated, thanks in advance
> 
> ```
> >>> hops: 3
> >>> device: cuda:0
> >>> seed: 2345
> >>> valset_ratio: 0
> >>> local_context_focus: cdm
> >>> SRD: 3
> >>> model_class: <class 'models.aoa.AOA'>
> >>> dataset_file: {'train': './datasets/omap/train_webform.xlsx', 'val': './datasets/omap/val_webform.xlsx', 'test': './datasets/omap/t
> est_webform.xlsx'}
> >>> inputs_cols: ['text_raw_indices1', 'aspect_indices1', 'text_raw_indices2', 'aspect_indices2']
> >>> optimizer_rec: sgd
> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> epoch: 1
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [92,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [93,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [94,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [95,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [32,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [33,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [34,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [35,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [36,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [37,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [38,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [39,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [40,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [41,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [42,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [43,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [44,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [45,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [46,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [47,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [48,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [49,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [50,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [51,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [52,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [53,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [54,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [55,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [56,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [57,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [58,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [59,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [60,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [61,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [62,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [11,0,0], thread: [63,0,0] Assertion `srcIndex < sr
> cSelectDimSize` failed.
> Traceback (most recent call last):
>   File "path\SMAT\train.py", line 346, in <module>
>     main()
>   File "path\SMAT\train.py", line 342, in main
>     ins.run()
>   File "path\Repos\SMAT\train.py", line 208, in run
>     best_model_path = self._train(criterion, optimizer, train_data_loader, val_data_loader, self.opt.lrshrink, self.opt.minlr)
>   File "path\SMAT\train.py", line 104, in _train
>     outputs = self.model(inputs)
>   File "path\anaconda3\envs\SMAT\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "path\SMAT\models\aoa.py", line 34, in forward
>     ctx1 = self.embed(text_raw_indices1)
>   File "path\anaconda3\envs\SMAT\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "path\anaconda3\envs\SMAT\lib\site-packages\torch\nn\modules\sparse.py", line 162, in forward
>     return F.embedding(
>   File "path\anaconda3\envs\SMAT\lib\site-packages\torch\nn\functional.py", line 2210, in embedding
>     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
> RuntimeError: CUDA error: device-side assert triggered
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> ```

This looks like the dimension of your embedding is not right. For the Glove, it should 300 dimension. Could you run it on our datasets provided? It will be a good start at the datasets we provided. :)

**Comment by Dome-s** [comment]
> This looks like the dimension of your embedding is not right. For the Glove, it should 300 dimension. Could you run it on our datasets provided? It will be a good start at the datasets we provided. :)

Hey thanks for the quick response, the dataset folder only contains these files which are not seperated into test/train/val 
imdb_saki_data.xlsx
omop_cms_data.xlsx
omop_mimic_data.xlsx
omop_synthea_data.xlsx
and none of the others(e.g the default webforms either) which is why i created my own attempt

**Comment by JZCS2018** [comment]
> > This looks like the dimension of your embedding is not right. For the Glove, it should 300 dimension. Could you run it on our datasets provided? It will be a good start at the datasets we provided. :)
> 
> Hey thanks for the quick response, the dataset folder only contains these files which are not seperated into test/train/val imdb_saki_data.xlsx omop_cms_data.xlsx omop_mimic_data.xlsx omop_synthea_data.xlsx and none of the others(e.g the default webforms either) which is why i created my own attempt

Hi, you can randomly partition the datasets we provided, or you should follow our data format. First make sure it can run on your end. I do not think there exists any issues on the model side. 
Let me know if you have any questions, please let me know!

**Comment by Dome-s** [comment]
> Hi, you can randomly partition the datasets we provided, or you should follow our data format. First make sure it can run on your end. I do not think there exists any issues on the model side. Let me know if you have any questions, please let me know!

i can not find the datasets in the repo.
the Datasets folder is almost empty

**Comment by JZCS2018** [comment]
> > Hi, you can randomly partition the datasets we provided, or you should follow our data format. First make sure it can run on your end. I do not think there exists any issues on the model side. Let me know if you have any questions, please let me know!
> 
> i can not find the datasets in the repo. the Datasets folder is almost empty

There are four raw datasets in our folder as you mentioned. You can paritition one of these datasets with any methods you are familiar with. 

Since these raw datasets follow the same format of the model inputs, you can use your partitioned datasets to test the model.

**Comment by Dome-s** [comment]
It works like that. Thank you for helping clear up my confusion!!
May i ask you a question regarding another modell you implemented and compard SMAT against in your Paper(specifically ADnEV ) or is this not the right place?

**Comment by JZCS2018** [comment]
> It works like that. Thank you for helping clear up my confusion!! May i ask you a question regarding another modell you implemented and compard SMAT against in your Paper(specifically ADnEV ) or is this not the right place?

Glad that you solved! Sorry I can not help you anything about other models. I will close this issue, since you have figured out.
